### ISSUE TITLE
WebPageTest

### ISSUE THREAD

**Issue by petraeeghen** [planetorium/portfolio#2]
Website did not pass the Cache Static Content section for the WebPageTest.

**Comment by catherine9** [comment]
**Pages & images** 3points- all the pages exist
**Personality & design** 3points- I REALLLY like how the website turned out, love the use of colours for each portfolio piece
**Image quality** 3 points - Quality of images is really good
**Accessibility** 3 points- each portfolio piece is accessible, not sure if "jump to main content" is supposed to show.
**Responsiveness** -3 points very responsive, like the margin for the text
**Performance** - 2 points, did not pass Cache Static content everything else is good 
**Code quality** 3 points code quality is good overall
